# Generated by Django 5.2.8 on 2025-12-05 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_card_cart_cartproduct_delete_cardproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='card',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='app.cart'),
            preserve_default=False,
        ),
    ]
